import os

SECRET_KEY = os.environ["SECRET_KEY"]
ALGORITHM = os.environ["ALGORITHM"]
SESSION_SECRET_KEY = os.environ["SESSION_SECRET_KEY"]
FRONTEND_URL = os.environ["FRONTEND_URL"]
ACCESS_TOKEN_EXPIRE_MINUTES = os.environ["ACCESS_TOKEN_EXPIRE_MINUTES"]