"""update documents table with user_id

Revision ID: 222e1db6198d
Revises: 62cef1c3415a
Create Date: 2026-08-22 13:17:49.419310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222e1db6198d'
down_revision: Union[str, Sequence[str], None] = '62cef1c3415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
